apiVersion: v1
kind: PersistentVolume
metadata:
  name: order-data-pv
spec:
  capacity:
    storage: "1Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data